import type { ShowcaseItem, ShowcasePageData } from './types.js'

function serializeItem(item: ShowcaseItem): string {
  const { _localImagePath, preview, ...rest } = item as ShowcaseItem & { _localImagePath?: string }
  const previewJs = _localImagePath
    ? `require(${JSON.stringify(_localImagePath)})`
    : JSON.stringify(preview ?? null)
  const inner = JSON.stringify(rest).slice(1, -1)
  return inner ? `{"preview":${previewJs},${inner}}` : `{"preview":${previewJs}}`
}

export function generateShowcaseModule(data: ShowcasePageData): string {
  const itemsJs = data.items.map(serializeItem).join(',')
  return (
    `// @generated by @homotechsual/docusaurus-plugin-showcase\n` +
    `module.exports = {"items":[${itemsJs}],"options":${JSON.stringify(data.options)}};\n`
  )
}
